- name: 1. Reset UFW
  community.general.ufw:
#   state: disabled / enabled / reloaded / reset
#     Disable ufw on boot, and unload ufw
#     Enable ufw on boot, and reload ufw
    state: reset # Reset to installation defaults & disable UFW

- name: 2. Protect against brute-force login attacks via SSH
  community.general.ufw:
    rule: limit # allow / deny / limit / reject
    port: "{{ item }}"
    proto: tcp
  loop:
  - '22'
  - '80'
  - '443'

- name: 3. Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming